#name: Production Release
#
#on:
#  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'
#
#jobs:
#  build:
#    name: Generate release name
#
#    steps:
#      - name: Commit latest version
#        run:
#          latest_version="$(git describe --match "[0-9]*\.[0-9]*\.[0-9]*" --abbrev=0 --tags)"
#          change_to="versionName "\"$latest_version"\""
#          sed -i "0,/versionName/{s/.*versionName.*/$change_to/}" buffer-android-app/build.gradle
#          git commit -m "Bump version release for $latest_version" -a
#
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          branch: release/beta
#          github_token: ${{ secrets.GITHUB_TOKEN } }
name: Android CI
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

#      - name: Runt lint
#        run: ./gradlew ktlintCheck

      - name: Build assemble release apk
        run: ./gradlew assembleRelease

      - name: Upload Apk
        uses: actions/upload-artifact@v3
        with:
          name: android-artifact
          path: app/build/outputs/apk/release


